#!/usr/bin/env python3
"""Generate lef/sg13g2_stdcell_hv.lef from the drawn GDS.

Geometry comes from the GDS alone: pin ports are the connected groups of
Metal1.pin (8/2) shapes, each labelled by the Metal1.text (8/25) label it
contains; the OBS block is the drawn Metal1 minus the pin geometry, so a
router cannot short a non-pin strap. Pin metadata that layout cannot express
-- DIRECTION, USE, SHAPE, NETEXPR, and the macro CLASS (SPACER for
fill/decap, ANTENNACELL for the antenna diode) -- is taken from the PDK's
thin-oxide LEF, whose pin names this library shares by construction.

Antenna attributes are recomputed, not copied: the thin-oxide values are
wrong for 3.5x longer gates. ANTENNAGATEAREA of an input pin is the summed
W x L of the devices whose gate is that pin's net; ANTENNADIFFAREA of an
output pin is the summed drain/source diffusion area (`ad`/`as`, already
validated against the vendor formulas) of the devices whose drain or source
is that net. Both come from the SPICE netlist.

The SITE is 0.48 x 7.140 um: the vertical routing pitch of the tech LEF by
17 horizontal routing tracks. Every cell width is a SITE multiple
(pad_to_site in layout_retarget.py) and every height is exactly the site
height; both are asserted here rather than trusted.
"""
import re
import pathlib
import klayout.db as db

HV = pathlib.Path("/foss/designs/sg13g2_stdcell_hv")
GDS = HV / "gds" / "sg13g2_stdcell_hv.gds"
SPICE = HV / "spice" / "sg13g2_stdcell_hv.spice"
LV_LEF = pathlib.Path("/foss/pdks/ihp-sg13g2/libs.ref/sg13g2_stdcell/lef"
                      "/sg13g2_stdcell.lef")
OUT = HV / "lef" / "sg13g2_stdcell_hv.lef"

SITE_NAME = "CoreSiteHV"
SITE_W, SITE_H = 0.48, 7.14
EPS = 1e-6


def f(v):
    """LEF-friendly number: no trailing zeros, no negative zero."""
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def parse_lv_lef():
    """{lv cell: {'class': str, 'pins': {pin: [metadata lines]}}}"""
    txt = LV_LEF.read_text()
    out = {}
    for m in re.finditer(r"^MACRO (\S+)\n(.*?)^END \1\s*$", txt,
                         re.S | re.M):
        name, body = m.group(1), m.group(2)
        cls = re.search(r"CLASS ([^;]+);", body).group(1).strip()
        pins = {}
        for pm in re.finditer(r"^  PIN (\S+)\n(.*?)^  END \1\s*$", body,
                              re.S | re.M):
            keep = []
            for ln in pm.group(2).splitlines():
                s = ln.strip()
                # metadata only; geometry and antenna values are regenerated
                if s.startswith(("DIRECTION", "USE", "SHAPE", "NETEXPR")):
                    keep.append(s)
            pins[pm.group(1)] = keep
        out[name] = {"class": cls, "pins": pins}
    return out


def spice_devices():
    """{hv cell: [(drain, gate, source, w*l um^2, ad um^2, as um^2)]}"""
    out, cur = {}, None
    for ln in SPICE.read_text().splitlines():
        s = ln.strip()
        low = s.lower()
        if low.startswith(".subckt"):
            cur = s.split()[1]
            out[cur] = []
        elif low.startswith(".ends"):
            cur = None
        elif cur and re.match(r"x\S+\s", low):
            t = s.split()
            if len(t) < 6 or not t[5].startswith("sg13_hv_"):
                continue
            d, g, srcn = t[1], t[2], t[3]

            def val(key):
                mm = re.search(rf"\b{key}=([0-9.e+-]+)([a-z]*)", low)
                if not mm:
                    return 0.0
                v = float(mm.group(1))
                scale = {"u": 1e-6, "n": 1e-9, "p": 1e-12, "f": 1e-15,
                         "": 1.0}[mm.group(2)]
                return v * scale
            w, l = val("w"), val("l")
            out[cur].append((d, g, srcn, w * l * 1e12,
                             val("ad") * 1e12, val("as") * 1e12))
    return out


def main():
    lv = parse_lv_lef()
    devs = spice_devices()

    ly = db.Layout()
    ly.read(str(GDS))
    lb = ly.layer(189, 4)
    # (LEF layer name, gds layer): drawing datatype 0, pin 2, text 25.
    # sdfbbp_1 is the one cell that routes a pin (D) up to Metal2 through
    # Via1; every other cell is Metal1-only.
    METALS = [("Metal1", 8), ("Metal2", 10)]
    lvia = ly.layer(19, 0)

    lines = [
        "# sg13g2_stdcell_hv -- thick-oxide (3.3 V) standard cells",
        "# Generated by work/gen_lef.py from the drawn GDS; see that script",
        "# for what is measured and what is inherited from the thin-oxide",
        "# LEF. Uses the PDK tech LEF (sg13g2_tech.lef) layers.",
        "VERSION 5.8 ;",
        'BUSBITCHARS "[]" ;',
        'DIVIDERCHAR "/" ;',
        "",
        f"SITE  {SITE_NAME}",
        "    CLASS       CORE ;",
        "    SYMMETRY    Y ;",
        f"    SIZE        {f(SITE_W)} BY {f(SITE_H)} ;",
        f"END  {SITE_NAME}",
        "",
    ]

    n_cells = 0
    for ci in sorted(ly.each_cell(), key=lambda c: c.name):
        cell = ly.cell(ci.cell_index())
        name = cell.name
        lvname = name.replace("sg13g2_hv_", "sg13g2_")
        meta = lv.get(lvname)
        assert meta, f"{name}: no thin-oxide LEF reference"
        bnd = [s.dbbox() for s in cell.shapes(lb).each()][0]
        W, H = round(bnd.width(), 4), round(bnd.height(), 4)
        assert abs(H - SITE_H) < EPS, f"{name}: height {H} != site {SITE_H}"
        assert abs(W / SITE_W - round(W / SITE_W)) < 1e-4, \
            f"{name}: width {W} not a site multiple"

        # pin geometry per metal: connected groups of the pin datatype,
        # labelled by the text each group contains
        pin_rects = {}            # pin -> {lef layer: [DBox]}
        pin_groups = {}           # lef layer -> merged pin Region
        for lname, gl in METALS:
            lpin = ly.layer(gl, 2)
            ltext = ly.layer(gl, 25)
            groups = db.Region(cell.shapes(lpin)).merged()
            pin_groups[lname] = groups
            texts = [(s.text.string,
                      db.Point(s.text.x, s.text.y))
                     for s in cell.shapes(ltext).each() if s.is_text()]
            raw = [s.dbbox() for s in cell.shapes(lpin).each()
                   if not s.is_text()]
            for g in groups.each():
                gb = db.Region(g)
                label = None
                for t, ip in texts:
                    if not (gb & db.Region(db.Box(ip.x - 1, ip.y - 1,
                                                  ip.x + 1, ip.y + 1))).is_empty():
                        label = t
                        break
                assert label, \
                    f"{name}: {lname} pin group without a label at {g.bbox()}"
                mine = [b for b in raw
                        if not (gb & db.Region(db.Box(
                            int(b.left * 1000) + 1, int(b.bottom * 1000) + 1,
                            int(b.right * 1000) - 1,
                            int(b.top * 1000) - 1))).is_empty()]
                pin_rects.setdefault(label, {}).setdefault(
                    lname, []).extend(mine)

        # vias belong to the pin whose metal they join
        via_rects = {}
        via_left = db.Region(cell.shapes(lvia)).merged()
        for pin, per in pin_rects.items():
            if "Metal2" not in per:
                continue
            m2 = db.Region()
            for b in per["Metal2"]:
                m2.insert(db.Box(int(b.left * 1000), int(b.bottom * 1000),
                                 int(b.right * 1000), int(b.top * 1000)))
            mine = via_left & m2
            if not mine.is_empty():
                via_rects[pin] = [p.bbox() for p in mine.each()]
                via_left -= mine

        assert set(pin_rects) == set(meta["pins"]), \
            f"{name}: pins {sorted(pin_rects)} != LEF ref {sorted(meta['pins'])}"

        lines.append(f"MACRO {name}")
        lines.append(f"  CLASS {meta['class']} ;")
        lines.append("  ORIGIN 0 0 ;")
        lines.append(f"  FOREIGN {name} 0 0 ;")
        lines.append(f"  SIZE {f(W)} BY {f(H)} ;")
        lines.append("  SYMMETRY X Y ;")
        lines.append(f"  SITE {SITE_NAME} ;")

        for pin, mlines in meta["pins"].items():
            per = pin_rects[pin]
            lines.append(f"  PIN {pin}")
            for s in mlines:
                lines.append(f"    {s}")
            # antenna values from the netlist, for signal pins only. The
            # CAR-ratio attributes of the thin-oxide LEF are not emitted:
            # they are derived quantities, and faking them is worse than
            # letting the router compute its own.
            if not any("POWER" in s or "GROUND" in s for s in mlines):
                gate = sum(a for d_, g_, s_, a, _, _ in devs.get(name, [])
                           if g_ == pin)
                diff = sum((ad if d_ == pin else 0) + (asr if s_ == pin else 0)
                           for d_, g_, s_, _, ad, asr in devs.get(name, []))
                if pin in via_rects:
                    cut = sum((b.width() / 1000) * (b.height() / 1000)
                              for b in via_rects[pin])
                    lines.append(f"    ANTENNAPARTIALCUTAREA {cut:.4f} "
                                 "LAYER Via1 ;")
                if any("INPUT" in s for s in mlines) and gate > 0:
                    lines.append("    ANTENNAMODEL OXIDE1 ;")
                    for lname in per:
                        lines.append(f"      ANTENNAGATEAREA {gate:.4f} "
                                     f"LAYER {lname} ;")
                if any("OUTPUT" in s for s in mlines) and diff > 0:
                    lines.append(f"    ANTENNADIFFAREA {diff:.4f} "
                                 "LAYER Metal1 ;")
            lines.append("    PORT")
            for lname in ("Metal1", "Metal2"):
                if lname not in per:
                    continue
                lines.append(f"      LAYER {lname} ;")
                for b in per[lname]:
                    lines.append(f"        RECT {f(b.left)} {f(b.bottom)} "
                                 f"{f(b.right)} {f(b.top)} ;")
            if pin in via_rects:
                lines.append("      LAYER Via1 ;")
                for b in via_rects[pin]:
                    lines.append(f"        RECT {f(b.left / 1000)} "
                                 f"{f(b.bottom / 1000)} {f(b.right / 1000)} "
                                 f"{f(b.top / 1000)} ;")
            lines.append("    END")
            lines.append(f"  END {pin}")

        # OBS: drawn metal the pins do not cover, plus unassigned vias.
        # Region-level decomposition: polygons here can carry holes (a pin
        # cut out of the middle of a strap), and a hull-based decomposition
        # would fill the hole and block the pin with OBS metal.
        obs_out = []
        for lname, gl in METALS:
            obs = (db.Region(cell.shapes(ly.layer(gl, 0))).merged()
                   - pin_groups[lname]).merged()
            boxes = []
            for tp in obs.decompose_trapezoids_to_region().each():
                bb = tp.bbox()
                boxes.append((bb.left / 1000, bb.bottom / 1000,
                              bb.right / 1000, bb.top / 1000))
            if boxes:
                obs_out.append((lname, sorted(boxes)))
        if not via_left.is_empty():
            obs_out.append(("Via1", sorted(
                (p.bbox().left / 1000, p.bbox().bottom / 1000,
                 p.bbox().right / 1000, p.bbox().top / 1000)
                for p in via_left.each())))
        if obs_out:
            lines.append("  OBS")
            for lname, boxes in obs_out:
                lines.append(f"      LAYER {lname} ;")
                for x0, y0, x1, y1 in boxes:
                    lines.append(f"        RECT {f(x0)} {f(y0)} "
                                 f"{f(x1)} {f(y1)} ;")
            lines.append("  END")
        lines.append(f"END {name}")
        lines.append("")
        n_cells += 1

    lines.append("END LIBRARY")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {n_cells} macros, site {SITE_NAME} "
          f"{SITE_W} x {SITE_H}")


if __name__ == "__main__":
    main()
