#!/usr/bin/env python3
"""Build a gallery schematic for sg13g2_stdcell_hv.

The PDK ships IHP130_stdcells.sch, a flat schematic that places one instance of
every thin-oxide standard cell so you can see the whole library at once. This
makes the equivalent for the thick-oxide library.

Two differences from the PDK's version: it covers all 84 cells rather than a
subset, and the placement is computed from each symbol's actual drawn extent
rather than hand-placed, so nothing overlaps whatever the pin count.
"""
import re, pathlib, math

HV = pathlib.Path("/foss/designs/sg13g2_stdcell_hv")
SYM = HV / "sym" / "xschem"
OUT = HV / "sch" / "xschem" / "sg13g2_hv_stdcells.sch"

GRID = 10          # xschem snap
COL_GAP = 60       # clear space between columns
ROW_GAP = 40       # clear space between symbols in a column
HEAD = 60          # space under a group heading

# Functional grouping, in the order the columns appear.
GROUPS = [
    ("Inverters / buffers", r"^(inv|buf)_"),
    ("NAND",                r"^nand"),
    ("NOR",                 r"^nor"),
    ("AND",                 r"^and"),
    ("OR",                  r"^or"),
    ("AND-OR / OR-AND",     r"^(a\d|o\d)"),
    ("XOR / MUX",           r"^(xor|xnor|mux)"),
    ("Tri-state",           r"^(ebufn|einvn)"),
    ("Flip-flops",          r"^(dfrbp|dfrbpq|sdf)"),
    ("Latches",             r"^(dlh|dll)"),
    ("Clock gating",        r"^(lgcp|slgcp)"),
    ("Delay / hold",        r"^(dlygate|sighold)"),
    ("Tie / fill / decap",  r"^(tiehi|tielo|fill|decap|antenna)"),
]


def sym_bbox(path):
    """Drawn extent of a symbol, from its geometry records.

    L=line, B=box, P=polygon, A=arc, T=text. Pin boxes (B on layer 5) count,
    because they are what the wires attach to.
    """
    xs, ys = [], []
    for line in path.read_text().splitlines():
        t = line.split()
        if not t:
            continue
        k = t[0]
        try:
            if k == "L" and len(t) >= 6:
                v = [float(x) for x in t[2:6]]
                xs += [v[0], v[2]]; ys += [v[1], v[3]]
            elif k == "B" and len(t) >= 6:
                v = [float(x) for x in t[2:6]]
                xs += [v[0], v[2]]; ys += [v[1], v[3]]
            elif k == "A" and len(t) >= 5:
                x, y, r = float(t[2]), float(t[3]), float(t[4])
                xs += [x - r, x + r]; ys += [y - r, y + r]
            elif k == "P" and len(t) >= 4:
                n = int(t[2])
                v = [float(x) for x in t[3:3 + 2 * n]]
                xs += v[0::2]; ys += v[1::2]
        except (ValueError, IndexError):
            continue
    if not xs:
        return (-30.0, -30.0, 30.0, 30.0)
    return (min(xs), min(ys), max(xs), max(ys))


def snap(v):
    return int(round(v / GRID) * GRID)


def main():
    cells = sorted(p.stem for p in SYM.glob("*.sym"))
    short = {c: c[len("sg13g2_hv_"):] for c in cells}

    # assign each cell to the first group whose pattern matches
    assigned, columns = set(), []
    for title, pat in GROUPS:
        rx = re.compile(pat)
        members = [c for c in cells if c not in assigned and rx.match(short[c])]
        assigned |= set(members)
        if members:
            columns.append((title, members))
    leftover = [c for c in cells if c not in assigned]
    if leftover:
        columns.append(("Other", leftover))

    bboxes = {c: sym_bbox(SYM / f"{c}.sym") for c in cells}

    body, n = [], 0
    x_cursor = 0
    for title, members in columns:
        width = max(bboxes[c][2] - bboxes[c][0] for c in members)
        x_mid = x_cursor + width / 2

        body.append(f'T {{{title}}} {snap(x_cursor)} -40 0 0 0.4 0.4 '
                    f'{{layer=4}}')

        y = -HEAD
        for c in members:
            x0, y0, x1, y1 = bboxes[c]
            h = y1 - y0
            # place so the symbol's own origin lands correctly under the cursor
            px = snap(x_mid - (x0 + x1) / 2)
            py = snap(y - h - y0) if False else snap(y - (y1 - y0) - y0)
            n += 1
            body.append(
                f'C {{{c}.sym}} {px} {py} 0 0 '
                f'{{name=x{n} VDD=VDD VSS=VSS prefix=sg13g2_hv_}}')
            body.append(f'T {{{short[c]}}} {px + snap((x0 + x1) / 2) - 40} '
                        f'{py + snap(y1 - y0 + 8)} 0 0 0.25 0.25 {{layer=15}}')
            y -= h + ROW_GAP
        x_cursor += width + COL_GAP

    header = [
        "v {xschem version=3.4.7 file_version=1.2",
        "* sg13g2_stdcell_hv -- thick-oxide (3.3 V) standard cell gallery.",
        "*",
        "* One instance of every cell in the library, grouped by function.",
        "* The thick-oxide counterpart of the PDK's IHP130_stdcells.sch.",
        "*",
        "* Generated by work/gen_gallery.py -- do not edit by hand.",
        "}",
        "G {}", "K {}", "V {}", "S {}", "E {}",
        'T {sg13g2_stdcell_hv} 0 -1990 0 0 0.8 0.8 {layer=4}',
        'T {thick-oxide (3.3 V) standard cells for IHP SG13G2} '
        '0 -1940 0 0 0.4 0.4 {layer=4}',
        f'T {{{len(cells)} cells}} 0 -1900 0 0 0.4 0.4 {{layer=4}}',
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(header + body) + "\n")
    print(f"wrote {OUT}")
    print(f"{len(cells)} cells in {len(columns)} groups:")
    for title, members in columns:
        print(f"  {title:22s} {len(members):2d}  "
              f"{', '.join(short[c] for c in members[:4])}"
              f"{' ...' if len(members) > 4 else ''}")


if __name__ == "__main__":
    main()
