#!/usr/bin/env python3
"""Apply the sg13g2_stdcell_hv contribution to an IHP-Open-PDK checkout.

Targets the *dev* branch conventions (the branch IHP pull requests merge
into). dev keeps every standard-cell view under libs.ref -- commits
1c0757e0 / c90378d8 moved the xschem symbols and schematics INTO
libs.ref/sg13g2_stdcell/{sym,sch}/xschem, which is exactly this
repository's layout -- so the library drops in unchanged:

  libs.ref/sg13g2_stdcell_hv/{cdl,doc,gds,lef,lib,spice,verilog,sym,sch}
  libs.tech/librelane/sg13g2_stdcell_hv/                 (LibreLane SCL)
  libs.tech/klayout/tech/pymacros/sg13g2_stdcell_hv.lym
  libs.tech/xschem/xschemrc                              (2-line patch)
  libs.tech/librelane/config.tcl                         (HV corner block)

LibreLane support (added for PR #1103 rev. 2 after Simon Dorrer's smoke
test) is four pieces:
  * the SCL directory (site CoreSiteHV 0.48 x 7.14, HV cell maps, tracks,
    exclude lists, and sdfbbp_map.v -- the flip-flop techmap designs must
    reference via SYNTH_EXTRA_MAPPING_FILE, which LibreLane does not let
    a PDK set);
  * a conditional block in the PDK-level librelane/config.tcl -- the LIB
    dict, corner list and core voltage there hardcode the thin-oxide
    1.2 V liberty filenames, and LibreLane validates the LIB paths
    eagerly, so an HV run needs them overridden at the source;
  * a copy of the thin-oxide tech LEF into the HV lib's lef/ dir (the
    PDK config globs libs.ref/$STD_CELL_LIBRARY/lef/sg13g2_tech.lef and
    a missing file is a hard Tcl error);
  * the installed liberty is stripped to the cells that have a LEF macro
    (finalize_lib.strip_layoutless): the characterization data for the
    not-yet-drawn flops stays in this repo, but the PDK must not
    advertise timing for cells that cannot be placed.

The symbols keep their schematic="tcleval($::SG13G2_HV_SCH/...)" pointer.
Upstream's own stdcell symbols resolve schematics through the
hierarchy_config proc, which is hard-wired to the thin-oxide sch
directory; rather than generalize that proc (a maintainer decision), the
xschemrc patch defines ::SG13G2_HV_SCH next to the mirrored
XSCHEM_LIBRARY_PATH append -- two added lines, no existing line touched,
idempotent.

The KLayout macro gets the PDK-relative GDS candidate prepended
(tech/pymacros -> ../../../../libs.ref/sg13g2_stdcell_hv/gds/); upstream
registers no stdcell GDS as a KLayout library today, so the macro is
flagged as a maintainer question in the PR.

doc/ ships the celllist, ReleaseNotes.txt and the two reports in both PDF
and Markdown -- not work/, the README or the repo licence files (the PDK's top-level
Apache-2.0 covers the contribution; attribution lives in ReleaseNotes.txt
and per-file headers).

After applying, the schematics are netlisted through the installed
symbols with xschem USING THE CHECKOUT'S OWN (patched) xschemrc, and
every cell's device multiset is compared against the SPICE netlist --
the same gate verify_sch.py runs against this repository.

Usage: python3 make_pdk_pr.py --pdk <IHP-Open-PDK checkout root>
"""
import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

import finalize_lib
import verify_sch

HV = pathlib.Path(__file__).resolve().parent.parent
XSCHEM = "/foss/tools/bin/xschem"
LIB_NAME = "sg13g2_stdcell_hv_typ_3p30V_25C.lib"

ANCHOR_LL = 'set ::env(DEFAULT_CORNER) "nom_typ_1p20V_25C"'
BEGIN_LL = "# >>> sg13g2_stdcell_hv corners (generated by work/make_pdk_pr.py)"
END_LL = "# <<< sg13g2_stdcell_hv corners"

PATCH_LL = f'''

{BEGIN_LL}
# Thick-oxide (3.3 V) standard-cell library. Overrides the thin-oxide LIB
# dict / corner list / core voltage above, because LibreLane validates
# every LIB path eagerly and the thin-oxide entries name files that have
# nothing to do with a 3.3 V run.
#
# Only corners whose Liberty is actually present are registered. The
# library ships its typical corner first and gains fast/slow later, and a
# corner listed but not shipped fails at config load with a path error --
# so presence is tested here rather than assumed.
#
# The voltages match the PDK's own 3.3 V domain: sg13g2_io ships
# 3p3V/25C, 3p6V/m40C and 3p0V/125C, so each HV stdcell corner pairs with
# the pad-ring corner at the same supply and temperature.
if {{ $::env(STD_CELL_LIBRARY) eq "sg13g2_stdcell_hv" }} {{
    set ::env(VDD_PIN_VOLTAGE) "3.30"
    set ::env(LIB) [dict create]
    set _hv_corners [list]
    foreach {{_pat _hv _io}} {{
        "*_typ_3p30V_25C"   sg13g2_stdcell_hv_typ_3p30V_25C   sg13g2_io_typ_1p5V_3p3V_25C
        "*_fast_3p60V_m40C" sg13g2_stdcell_hv_fast_3p60V_m40C sg13g2_io_fast_1p65V_3p6V_m40C
        "*_slow_3p00V_125C" sg13g2_stdcell_hv_slow_3p00V_125C sg13g2_io_slow_1p35V_3p0V_125C
    }} {{
        set _hvlib $::env(PDK_ROOT)/$::env(PDK)/libs.ref/sg13g2_stdcell_hv/lib/$_hv.lib
        set _iolib $::env(PDK_ROOT)/$::env(PDK)/libs.ref/sg13g2_io/lib/$_io.lib
        if {{ [file exists $_hvlib] }} {{
            if {{ [file exists $_iolib] }} {{
                dict set ::env(LIB) $_pat "$_hvlib $_iolib"
            }} else {{
                dict set ::env(LIB) $_pat "$_hvlib"
            }}
            lappend _hv_corners "nom[string range $_pat 1 end]"
        }}
    }}
    set ::env(STA_CORNERS) [join $_hv_corners " "]
    set ::env(DEFAULT_CORNER) "nom_typ_3p30V_25C"
    unset _hv_corners _pat _hv _io _hvlib _iolib
}}
{END_LL}'''

ANCHOR = ("append XSCHEM_LIBRARY_PATH "
          ":${PDK_ROOT}/${PDK}/libs.ref/sg13g2_stdcell/sym/xschem")
PATCH = (
    "append XSCHEM_LIBRARY_PATH "
    ":${PDK_ROOT}/${PDK}/libs.ref/sg13g2_stdcell_hv/sym/xschem\n"
    "# thick-oxide stdcell symbols resolve their schematics through this\n"
    "set ::SG13G2_HV_SCH "
    "${PDK_ROOT}/${PDK}/libs.ref/sg13g2_stdcell_hv/sch/xschem\n")


def copy_libs_ref(pdk):
    ref = pdk / "ihp-sg13g2" / "libs.ref" / "sg13g2_stdcell_hv"
    if ref.exists():
        shutil.rmtree(ref)
    for d in ("cdl", "gds", "lef", "lib", "spice", "verilog", "sym", "sch"):
        shutil.copytree(HV / d, ref / d)
    doc = ref / "doc"
    doc.mkdir(parents=True)
    shutil.copy2(HV / "doc" / "sg13g2_stdcell_hv.celllist", doc)
    shutil.copy2(HV / "doc" / "ReleaseNotes.txt", doc)
    # Both renderings of each report ship: the PDF to read, the Markdown it
    # was built from. A PDF alone cannot be diffed in review, quoted in an
    # issue, or corrected by anyone but its author -- and these reports are
    # the documentation of how the Liberty numbers were obtained, so the
    # source belongs next to the artifact. doc/report/build.sh regenerates
    # the PDFs from the Markdown.
    for report in (HV / "doc" / "report").glob("*.pdf"):
        shutil.copy2(report, doc)
    for report in (HV / "doc" / "report").glob("*.md"):
        shutil.copy2(report, doc)
    n = sum(1 for p in ref.rglob("*") if p.is_file())
    print(f"libs.ref/sg13g2_stdcell_hv: {n} files")
    return ref


def copy_tech_lef(pdk, ref):
    """The PDK-level librelane config globs
    libs.ref/$STD_CELL_LIBRARY/lef/sg13g2_tech.lef; Tcl glob errors on no
    match. Copy the checkout's own thin-oxide tech LEF so the two SCLs
    can never diverge in layer definitions."""
    src = (pdk / "ihp-sg13g2" / "libs.ref" / "sg13g2_stdcell" / "lef" /
           "sg13g2_tech.lef")
    shutil.copy2(src, ref / "lef" / "sg13g2_tech.lef")
    print("lef/sg13g2_tech.lef: copied from sg13g2_stdcell")


def copy_librelane(pdk):
    dst = (pdk / "ihp-sg13g2" / "libs.tech" / "librelane" /
           "sg13g2_stdcell_hv")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(HV / "librelane", dst)
    n = sum(1 for p in dst.iterdir())
    print(f"libs.tech/librelane/sg13g2_stdcell_hv: {n} files")


def patch_librelane_config(pdk):
    cfg = pdk / "ihp-sg13g2" / "libs.tech" / "librelane" / "config.tcl"
    text = cfg.read_text()
    if BEGIN_LL in text:
        # Replace the previous block rather than skipping: the corner list
        # grows as corners are characterized, so "already patched" would
        # freeze a checkout at whatever it was first patched with.
        pre, rest = text.split(BEGIN_LL, 1)
        _, post = rest.split(END_LL, 1)
        cfg.write_text(pre.rstrip("\n") + PATCH_LL.rstrip() + post)
        print("librelane config.tcl: HV corner block refreshed")
        return
    if "sg13g2_stdcell_hv" in text:
        print("librelane config.tcl: patched by an older unmarked version, "
              "leaving it alone -- remove that block to re-patch")
        return
    assert ANCHOR_LL in text, "DEFAULT_CORNER line not found in config.tcl"
    cfg.write_text(text.replace(ANCHOR_LL, ANCHOR_LL + PATCH_LL, 1))
    print("librelane config.tcl: HV corner block added after DEFAULT_CORNER")


def patch_xschemrc(pdk):
    rc = pdk / "ihp-sg13g2" / "libs.tech" / "xschem" / "xschemrc"
    text = rc.read_text()
    if "sg13g2_stdcell_hv/sym/xschem" in text:
        print("xschemrc: already patched")
        return rc
    assert ANCHOR in text, "thin-oxide sym append not found in xschemrc"
    text = text.replace(ANCHOR, ANCHOR + "\n" + PATCH.rstrip(), 1)
    rc.write_text(text)
    print("xschemrc: 3 lines added after the thin-oxide sym append")
    return rc


def copy_klayout(pdk):
    src = HV / "klayout" / "pymacros" / "sg13g2_stdcell_hv.lym"
    dst = (pdk / "ihp-sg13g2" / "libs.tech" / "klayout" / "tech" /
           "pymacros" / src.name)
    old = ('        candidates.append(os.path.join(here, "..", "..", "gds",\n'
           '                                       LIB_NAME + ".gds"))')
    new = ('        candidates.append(os.path.join(\n'
           '            here, "..", "..", "..", "..", "libs.ref", LIB_NAME,\n'
           '            "gds", LIB_NAME + ".gds"))\n'
           '        candidates.append(os.path.join(here, "..", "..", "gds",\n'
           '                                       LIB_NAME + ".gds"))')
    text = src.read_text()
    assert old in text, "GDS candidate block not found in the .lym"
    dst.write_text(text.replace(old, new))
    print(f"klayout: {dst.name} (PDK-relative GDS path prepended)")


def verify_tracked(pdk):
    """Fail if anything just installed would be invisible to git.

    A view that git silently ignores is copied onto the filesystem, passes
    every local check that reads it, and then simply does not exist for
    anyone who clones the branch. That is exactly how the spice view was
    lost from the first three revisions of the PR: the PDK's root
    .gitignore carries `*.spice`, libs.ref/.gitignore re-includes only the
    `spice/` *directory*, and sg13g2_stdcell's own spice view predates the
    rule and is already tracked -- so nothing complained until a reviewer
    cloned the branch and LibreLane died on the missing
    CELL_SPICE_MODELS path. Check it here, where it is cheap.
    """
    if not (pdk / ".git").exists():
        print("git visibility: not a checkout, skipped")
        return True
    roots = [pdk / "ihp-sg13g2" / "libs.ref" / "sg13g2_stdcell_hv",
             pdk / "ihp-sg13g2" / "libs.tech" / "librelane" / "sg13g2_stdcell_hv",
             pdk / "ihp-sg13g2" / "libs.tech" / "klayout" / "tech" / "pymacros"]
    files = [p for r in roots for p in r.rglob("*") if p.is_file()]
    rel = [str(p.relative_to(pdk)) for p in files]
    # --no-index is essential: without it check-ignore stays silent about a
    # path that is already staged, so the check would pass the moment
    # someone force-added the file and would never flag the rule that
    # dropped it in the first place.
    r = subprocess.run(["git", "-C", str(pdk), "check-ignore", "--stdin",
                        "--no-index"],
                       input="\n".join(rel), capture_output=True, text=True)
    ignored = [ln for ln in r.stdout.splitlines() if ln.strip()]
    if ignored:
        print(f"  FAIL git visibility: {len(ignored)} installed file(s) are "
              f"ignored and would never reach the PR:")
        for f in ignored[:20]:
            print(f"    {f}")
        return False
    print(f"git visibility: all {len(rel)} installed files are trackable")
    return True


def verify_install(pdk):
    """Netlist all schematics through the installed symbols, with the
    checkout's own xschemrc, and compare devices against SPICE."""
    spice = verify_sch.spice_cells()
    sch_dir = (pdk / "ihp-sg13g2" / "libs.ref" / "sg13g2_stdcell_hv" /
               "sch" / "xschem")
    cells = sorted(p.stem for p in sch_dir.glob("sg13g2_hv_*.sch")
                   if p.stem != "sg13g2_hv_stdcells")
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="pdkinstall_"))
    (tmp / "xschemrc").write_text(
        f"set ::env(PDK) ihp-sg13g2\n"
        f"set ::env(PDK_ROOT) {pdk}\n"
        f"source {pdk}/ihp-sg13g2/libs.tech/xschem/xschemrc\n"
        f"set netlist_dir {tmp}\n")
    (tmp / "all_cells.sch").write_text(verify_sch.wrapper(cells))
    subprocess.run([XSCHEM, "--rcfile", str(tmp / "xschemrc"), "-n", "-q",
                    "--no_x", str(tmp / "all_cells.sch")],
                   cwd=tmp, capture_output=True, text=True, timeout=1800)
    txt = (tmp / "all_cells.spice").read_text()
    bad = 0
    for cell in cells:
        m = re.search(rf"^\.subckt\s+{re.escape(cell)}\s", txt, re.M)
        if not m:
            print(f"  FAIL {cell}: no .subckt emitted")
            bad += 1
            continue
        body = txt[m.end():txt.index(".ends", m.end())]
        if verify_sch.devices(body) != spice[cell][1]:
            print(f"  FAIL {cell}: devices differ from SPICE")
            bad += 1
    shutil.rmtree(tmp, ignore_errors=True)
    print(f"install netlist check (checkout xschemrc): "
          f"{len(cells) - bad}/{len(cells)} cells match the SPICE netlist")
    return bad == 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdk", required=True,
                    help="IHP-Open-PDK checkout root (on the dev branch)")
    args = ap.parse_args()
    pdk = pathlib.Path(args.pdk).resolve()
    assert (pdk / "ihp-sg13g2" / "libs.ref").is_dir(), \
        f"{pdk} is not an IHP-Open-PDK checkout"

    ref = copy_libs_ref(pdk)
    copy_tech_lef(pdk, ref)
    finalize_lib.strip_layoutless(ref / "lib" / LIB_NAME,
                                  ref / "lef" / "sg13g2_stdcell_hv.lef")
    copy_librelane(pdk)
    patch_librelane_config(pdk)
    patch_xschemrc(pdk)
    copy_klayout(pdk)
    ok = verify_install(pdk)
    ok = verify_tracked(pdk) and ok

    print("""
Next steps in the checkout (PRs target the dev branch; commits need a
Developer Certificate of Origin sign-off, i.e. git commit -s):
  re-run signoff with the checkout's decks: run_drc.py on the two
    work/drc arrays, per-cell LVS, OpenSTA read of the .lib, iverilog
    against the checkout's sg13g2_udp.v;
  smoke-test LibreLane: STD_CELL_LIBRARY: sg13g2_stdcell_hv plus, at
    design level, SYNTH_EXTRA_MAPPING_FILE:
    pdk_dir::libs.tech/librelane/sg13g2_stdcell_hv/sdfbbp_map.v
    (flip-flops; the variable is not PDK-scoped in LibreLane);
  branch from dev, commit, push to a fork, open the PR as a draft;
  flag as maintainer questions: cell set (view_matrix.py), the KLayout
    macro, hierarchy_config unification, missing qucs-s views, and the
    IO liberty paired with the HV corner (sg13g2_io_typ_1p5V_3p3V_25C is
    the closest existing file; none is characterized for a 3.3 V core).
""")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
