#!/bin/sh
# Build the shipped reports: Markdown -> HTML -> PDF.
#
# This recipe used to live only in shell history, which meant the PDFs in
# libs.ref/.../doc/ could not be regenerated by anyone but the author -- and a
# report that cannot be rebuilt from its source is not really a source file.
#
# Chain:
#   pandoc     markdown -> standalone HTML, using the ChipDesign template/CSS
#   texmath_svg.py  a pandoc filter that renders TeX math to cached SVGs with
#                   matplotlib mathtext, because WeasyPrint cannot lay out
#                   MathML and we do not want a LaTeX engine in the loop
#   weasyprint HTML -> PDF
#
# Usage:  ./build.sh [name ...]     (default: both reports)
set -e

HERE=$(cd "$(dirname "$0")" && pwd)
cd "$HERE"

DOCS=${*:-"stdcell_characterization_methods sg13g2_stdcell_hv_report"}

for d in $DOCS; do
    [ -f "$d.md" ] || { echo "no such report: $d.md" >&2; exit 1; }
    echo "--- $d ---"

    pandoc "$d.md" \
        --from markdown+tex_math_dollars+pipe_tables+fenced_code_attributes \
        --to html5 --standalone \
        --template chipdesign.html --css chipdesign.css \
        --filter ./texmath_svg.py \
        --toc --toc-depth=2 \
        -o "$d.html"

    # -u . resolves the CSS, the logo and the _mathcache SVGs relative to here
    python3 -m weasyprint "$d.html" "$d.pdf" -u .

    rm -f "$d.html"
    echo "    $d.pdf  $(wc -c < "$d.pdf") bytes"
done
